# Latest golang image on alpine linux
FROM golang:1.22.5-alpine3.20

# Work directory
WORKDIR /groupie-tracker

# Installing dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copying all the files
COPY . .

# Build the Go app
RUN go build -o main .

# Expose port 5000 to the outside world
EXPOSE 5000

# Command to run the executable
CMD ["./main"]
